baseURL = ''
title = 'glitched echoes'

theme = 'DoIt'
themesDir = 'themes'

languageCode = 'en-us'
defaultContentLanguage = "en"
languageName = "English"

hasCJKLanguage = false
googleAnalytics = ""
copyright = ""
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
