defaultTheme = "auto"
gitRepo = "https://github.com/fenrir-san/fenrir-san.github.io"
fingerprint = ""
enablePWA = true
dateFormat = "2006-01-02"
title = "glitched echoes"
description = ""
images = []
bundle = true

[author]
name = "fenrir"
email = "fenrir.dev@tutamail.me"
link = "https://fenrir.is-a.dev"

[header]
desktopMode = "fixed"
mobileMode = "auto"

[header.title]
logo = ""
name = "glitched echoes"
pre = ""
post = ""
typeit = true

[footer]
enable = true
custom = ""
hostedOn = '<a title="is-a.dev" href="https://www.is-a.dev/" target="_blank" rel="noopener noreffer">is-a.dev</a>'
hugo = false
copyright = true
author = true
since = 2024
icp = ""
license = '<a rel="license external nofollow noopener noreffer" href="https://opensource.org/licenses/GPL-3.0" target="_blank">GPL-3.0</a>'

[home.profile]
enable = true
gravatarEmail = "fenrir.dev@tutamail.me"
avatarURL = ""
title = "Salutations, Voyagers."
subtitle = "I am Fenrir, a wayfarer traversing the digital wastelands in search of hidden truths buried deep within the chaos. These words are for those who seek to uncover the unknown, so they may forge a brighter world from the shadows."
typeit = true
social = true
disclaimer = "May the knowledge that rests here change your view of the unseen world."

[home.posts]
enable = true
paginate = 6

[home.projects]
enable = true
paginate = 6

[social]
GitHub = "fenrir-san"
Linkedin = "vineet-pratik-agarwal"
Stackoverflow = ""
Steam = ""
Mastodon = "@fenrir-san"
Ko-Fi = "fenrir"
Email = "fenrir.dev@tutamail.me"
RSS = true # DoIt NEW | 0.2.0

[search]
enable = false
type = "fuse"
contentLength = 4000
placeholder = ""
maxResultLength = 10
snippetLength = 30
highlightTag = "em"
absoluteURL = false

[search.fuse]
# DoIt NEW | 0.2.12 https://fusejs.io/api/options.html
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

[page]
hiddenFromHomePage = false
hiddenFromSearch = false
seriesNavigation = true
twemoji = true
lightgallery = true
ruby = true
fraction = true
linkToMarkdown = true
rssFullText = false
pageStyle = "normal"

[page.toc]
enable = true
keepStatic = false
auto = true

[page.code]
copy = true
maxShownLines = 50

[page.math]
enable = true
blockLeftDelimiter = '\['
blockRightDelimiter = '\]'
inlineLeftDelimiter = '\('
inlineRightDelimiter = '\)'
copyTex = true
mhchem = true

[page.mapbox]
accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
navigation = true
geolocate = true
scale = true
fullscreen = true

[page.share]
enable = true
Twitter = true
Facebook = true
Linkedin = true
Whatsapp = true
Mastodon = true
Pinterest = false
Tumblr = false
HackerNews = false
Reddit = true
Pocket = false
Evernote = false
Trello = false

[app]
title = "glitched echoes"
noFavicon = true
svgFavicon = "/favicons/favicon.ico"
themeColor = "#ffffff"
iconColor = "#5bbad5"
tileColor = "#da532c"

[compatibility]
polyfill = true
objectFit = true
